
name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: deploy to ec2 instance
      uses: appleboy/ssh-action@master
      env:
        PATH: "/home/ubuntu/.local/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_ENDPOINT: ${{secrets.DB_ENDPOINT}}
        DB_NAME: ${{secrets.DB_NAME}}
        S3_BUCKET_NAME: ${{secrets.ARTIFACTS_S3_BUCKET}}
      with:
        host: ${{secrets.MLFLOW_EC2_HOST}}
        username: ${{secrets.MLFLOW_EC2_USERNAME}}
        key: ${{secrets.MLFLOW_EC2_KEY}}
        envs: PATH, DB_USER, DB_PASSWORD, DB_ENDPOINT, DB_NAME, S3_BUCKET_NAME
        script: |
          fuser -k 5000/tcp
          mlflow server \
          -h 0.0.0.0 -p 5000 --backend-store-uri \
          postgresql://${DB_USER}:${DB_PASSWORD}@${DB_ENDPOINT}:5432/${DB_NAME} \
          --default-artifact-root ${S3_BUCKET_NAME} --serve-artifacts

        