
name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ca-central-1                  # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{secrets.MLFLOW_ECR_REPOSITORY_NAME}}          # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: deploy to ec2 instance
      env:
        IMAGE: ${{steps.build-image.outputs.image}}
        ECR_PASSWORD: ${{secrets.ECR_LOGIN_PASSWORD}}
        REGION: ${{env.AWS_REGION}}
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.MLFLOW_EC2_HOST}}
        username: ${{secrets.MLFLOW_EC2_USERNAME}}
        key: ${{secrets.MLFLOW_EC2_KEY}}
        # envs: IMAGE, ECR_PASSWORD, REGION
        script: |
          fuser -k 5000/tcp
          mlflow server -h 0.0.0.0 -p 5000 \
          --backend-store-uri postgresql://${DB_USER}:${DB_PASSWORD}@${DB_ENDPOINT}:5432/${DB_NAME} \
           --default-artifact-root ${S3_BUCKET_NAME} --serve-artifacts
          # rm -rf tweets-sentiment-analysis
          # git clone https://github.com/Madhavan7/tweets-sentiment-analysis.git
          # sh ./tweets-sentiment-analysis/mlflow-setup.sh
        